version: 2

sources:
  - name: source_adventureworks
    description: Base de dados de vendas da Adeventureworks.
    database: FEA24_9
    schema: RAW_ADVENTURE_WORKS
    tables:
      - name: PRODUCT
        description: Tabela fonte com as principais informações dos produtos da Aventureworks.
        columns:
          - name: PRODUCTID
            data_tests:
              - unique
              - not_null

      - name: PRODUCTCATEGORY
        description: Tabela fonte com informações das categorias dos produtos da Aventureworks.
        columns:
          - name: PRODUCTCATEGORYID
            data_tests:
              - unique
              - not_null


      - name: PRODUCTSUBCATEGORY
        description: Tabela fonte com informações das subcategorias dos produtos da Aventureworks.
        columns:
          - name: PRODUCTSUBCATEGORYID
            data_tests:
              - unique
              - not_null


      - name: CUSTOMER
        description: Tabela fonte com informações sobre os clientes da Aventureworks.
        columns:
          - name: CUSTOMERID
            data_tests:
              - unique
              - not_null


      - name: PERSON
        description: Tabela fonte com informações sobre as pessoas da Aventureworks.
        columns:
          - name: BUSINESSENTITYID
            data_tests:
              - unique
              - not_null

      
      - name: CREDITCARD
        description: Tabela fonte com informações sobre o tipo de cartão usado na compra.
        columns:
          - name: CREDITCARDID
            data_tests:
              - unique
              - not_null


      - name: SALESREASON
        description: Tabela fonte com informações sobre o motivo da compra realizada na Adventureworks.
        columns:
          - name: SALESREASONID
            data_tests:
              - unique
              - not_null

    
      - name: SALESORDERHEADER
        description: A tabela SalesOrderHeader contém informações gerais sobre os pedidos de vendas realizados na base de dados AdventureWorks, como status.
        columns:
          - name: SALESORDERID
            data_tests:
              - unique
              - not_null


  
  

